### ISSUE TITLE
jsii-docgen doesn't find child jsii packages in a monorepo with npm workspaces

### ISSUE THREAD

**Issue by TimothyJones** [cdklabs/jsii-docgen#1031]
Hi there,

in an npm monorepo with the following structure:

```
packages/
├─ child-jsii-package/
│  ├─ package.json
├─ parent-jsii-package/
│  ├─ package.json   # includes child-jsii-package
package.json
```

jsii-docgen works fine on `child-jsii-package`, but fails on the `parent-jsii-package` with:

```
Error: Assembly "child-jsii-package" not found
    at TypeSystem.findAssembly (/Users/home/office/maintainer/contractcase/node_modules/jsii-reflect/lib/type-system.js:147:19)
    at TypeSystem.findFqn (/Users/home/office/maintainer/contractcase/node_modules/jsii-reflect/lib/type-system.js:156:26)
    at get type [as type] (/Users/home/office/maintainer/contractcase/node_modules/jsii-reflect/lib/type-ref.js:52:28)
    at TypeScriptTranspile.typeReference (/Users/home/office/maintainer/contractcase/node_modules/jsii-docgen/lib/docgen/transpile/transpile.js:317:17)
    at TypeScriptTranspile.parameter (/Users/home/office/maintainer/contractcase/node_modules/jsii-docgen/lib/docgen/transpile/typescript.js:134:30)
    at /Users/home/office/maintainer/contractcase/node_modules/jsii-docgen/lib/docgen/transpile/typescript.js:156:73
    at Array.map (<anonymous>)
    at TypeScriptTranspile.callable (/Users/home/office/maintainer/contractcase/node_modules/jsii-docgen/lib/docgen/transpile/typescript.js:156:35)
    at new InstanceMethod (/Users/home/office/maintainer/contractcase/node_modules/jsii-docgen/lib/docgen/view/instance-method.js:10:37)
    at /Users/home/office/maintainer/contractcase/node_modules/jsii-docgen/lib/docgen/view/instance-methods.js:9:25
```

Other jsii commands work (with the exception of [this issue](https://github.com/aws/jsii/issues/4132), which affects non-jsii packages marked with `bundleDependencies`, so my guess is it is a different cause - but I'm mentioning it in case it isn't).

Let me know if you need any further information

**Comment by RomainMuller** [comment]
This is because `jsii-docgen` only loads `.jsii` assemblies it finds _under_ `$PWD`, and since some here are hoisted up, they're not loaded upfront nor resolved... so the `jsii-reflect` type system it builds up is incomplete...

Seems to me that it should actually resolve dependencies "as node would", so that it would work... I'm looking at this.

**Comment by TimothyJones** [comment]
Thank you so much!!
