### ISSUE TITLE
Cannot create docgen on a AwsCdkConstructLibrary from projen

### ISSUE THREAD

**Issue by furstenheim-goodnotes** [cdklabs/jsii-docgen#1122]
Hi, I'm trying to create a AwsCdkConstructLibrary with projen. This fails at a stage and I think the bug is down to a bug in jsii-docgen.

When running `yarn jsii-docgen` on the latest version, I get the following error:

``` 
Error: Invalid assembly:
0: instance.schema is not one of enum values: jsii/0.10.0
1: instance requires property "author"
2: instance requires property "description"
3: instance requires property "fingerprint"
4: instance requires property "homepage"
5: instance requires property "jsiiVersion"
6: instance requires property "license"
7: instance requires property "name"
8: instance requires property "repository"
9: instance requires property "version"

    at Object.validateAssembly (MY_FOLDER/node_modules/@jsii/spec/lib/validate-assembly.js:15:11)
    at Assembly.validate (MY_FOLDER/node_modules/jsii-reflect/lib/assembly.js:158:14)
    at TypeSystem._loadModule (MY_FOLDER/node_modules/jsii-reflect/lib/type-system.js:92:21)
    at async TypeSystem._loadModule (MY_FOLDER/node_modules/jsii-reflect/lib/type-system.js:107:17)
    at async TypeSystem.loadModule (MY_FOLDER/node_modules/jsii-reflect/lib/type-system.js:65:21)
    at async Object.renderSinglePageModule (MY_FOLDER/node_modules/jsii-docgen/lib/index.js:41:17)
    at async main (MY_FOLDER/node_modules/jsii-docgen/lib/cli.js:16:9)
error Command failed with exit code 1.
```

I've looked at the input that the files receive, and validate-assemply.js is receiving 

```
{
  schema: 'jsii/file-redirect',
  compression: 'gzip',
  filename: '.jsii.gz'
}
```
for the folder `node_modules/aws-cdk-lib/package.json`.

Projen, for example, unzips first the file before processing https://github.com/projen/projen/blob/ebd75ce77014cdb0c0daedf1b6de7b1f3157ecf9/src/inventory.ts#L118

**Comment by mrgrain** [comment]
Which version of `jsii-docgen`, `jsii-reflect` & `@jsii/spec` do you have installed? 

docgen isn't loading assemblies directly, so this sounds like one of your transitive dependencies is out of date.

**Comment by mrgrain** [comment]
Cannot reproduce with latest versions.
