### ISSUE TITLE
Error: Invalid assembly * must be string

### ISSUE THREAD

**Issue by Dazza65** [cdklabs/jsii-docgen#748]
The build 7.0.56 (use jsii's loadAssemblyFromFile function #723) causes the above error when using lerna v5.3.0

```
👾 build » post-compile | lerna run post-compile --stream
lerna notice cli v5.3.0
lerna info versioning independent
lerna info Executing command in 1 package: "npm run post-compile"
constructone: > constructone@0.0.0 post-compile
constructone: > npx projen post-compile
constructone: 👾 post-compile » docgen | jsii-docgen -o API.md
constructone: Error: Invalid assembly:
constructone:  * must be string
constructone:     at validateAssembly (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/@jsii/spec/lib/validate-assembly.js:12:15)
constructone:     at loadAssemblyFromBuffer (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/@jsii/spec/lib/assembly-utils.js:74:64)
constructone:     at loadAssemblyFromFile (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/@jsii/spec/lib/assembly-utils.js:100:12)
constructone:     at /home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/jsii-docgen/lib/docgen/view/documentation.js:222:62
constructone:     at async withTempDir (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/jsii-docgen/lib/docgen/view/documentation.js:271:16)
constructone:     at async Documentation.createAssembly (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/jsii-docgen/lib/docgen/view/documentation.js:212:25)
constructone:     at async Documentation.toJson (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/jsii-docgen/lib/docgen/view/documentation.js:125:28)
constructone:     at async Documentation.toMarkdown (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/jsii-docgen/lib/docgen/view/documentation.js:170:23)
constructone:     at async main (/home/ec2-user/development/patternlibrary/lp2/constructone/node_modules/jsii-docgen/lib/cli.js:51:21)
constructone: 👾 Task "post-compile » docgen" failed when executing "jsii-docgen -o API.md" (cwd: /home/ec2-user/development/patternlibrary/lp2/constructone)
lerna ERR! npm run post-compile exited 1 in 'constructone'
👾 Task "build » post-compile" failed when executing "lerna run post-compile --stream" (cwd: /home/ec2-user/development/patternlibrary/lp2)
```

**Comment by polothy** [comment]
Getting the same thing, using projen with a CDK Construct project. Got the error when I upgraded project dependencies.

**Comment by Dazza65** [comment]
Adding the following to the .projenrc.js provides a workaround for now

```
  bundledDeps: [
    'jsii-docgen@7.0.55'
  ],
```

**Comment by mrgrain** [comment]
Fixed in https://github.com/cdklabs/jsii-docgen/pull/1155
