### ISSUE TITLE
Facing Error: Assembly "@custom-cdk-constructs/base-pipeline" not found

### ISSUE THREAD

**Issue by anshulgargamway** [cdklabs/jsii-docgen#784]
Currently we are exploring a way to generate documentation for our custom CDK construct.

We have created custom CDK contruct using following command
`npx cdk init lib --language=typescript`

and we tried to execute 
`npx jsii-docgen`

And we faced following issue any help over here will be great.
`Error: Assembly "@custom-cdk-constructs/base-pipeline" not found
    at TypeSystem.findAssembly (C:\Users\masked\AppData\Local\npm-cache\_npx\6d618b10e1acde92\node_modules\jsii-reflect\lib\type-system.js:147:19)
    at C:\Users\masked\AppData\Local\npm-cache\_npx\6d618b10e1acde92\node_modules\jsii-docgen\lib\docgen\view\documentation.js:235:23
    at async withTempDir (C:\Users\masked\AppData\Local\npm-cache\_npx\6d618b10e1acde92\node_modules\jsii-docgen\lib\docgen\view\documentation.js:271:16)
    at async Documentation.createAssembly (C:\Users\masked\AppData\Local\npm-cache\_npx\6d618b10e1acde92\node_modules\jsii-docgen\lib\docgen\view\documentation.js:212:25)
    at async Documentation.toJson (C:\Users\masked\AppData\Local\npm-cache\_npx\6d618b10e1acde92\node_modules\jsii-docgen\lib\docgen\view\documentation.js:125:28)
    at async Documentation.toMarkdown (C:\Users\masked\AppData\Local\npm-cache\_npx\6d618b10e1acde92\node_modules\jsii-docgen\lib\docgen\view\documentation.js:170:23)
    at async main (C:\Users\masked\AppData\Local\npm-cache\_npx\6d618b10e1acde92\node_modules\jsii-docgen\lib\cli.js:51:21)`

Do we need to do anything additional on our newly created construct apart from executing `npx jsii-docgen`

**Comment by vdahlberg** [comment]
Did you solve this?

Facing the same issue, but it works with a new project generated using (projen)[https://github.com/projen/projen] and awscdk-construct project type.

But we would prefer to not use projen.

**Comment by mrgrain** [comment]
Are you able to confirm if this happens only on windows? I suspect it's due to failing to resolve modules correctly on windows.
