### ISSUE TITLE
Lacking build steps

### ISSUE THREAD

**Issue by mbonig** [cdklabs/jsii-docgen#833]
Cloning, running `yarn` and then `yarn build` does not result in a clean build. It fails during unit testing with the following error:

```
 FAIL  test/docgen/view/documentation.test.ts (347.879 s)

...

  ● package installation does not run lifecycle hooks

    Command failed: yarn package
    [jsii-pacmak] [WARN] Failed building python
    [jsii-pacmak] [WARN] python failed
    Error: Command (python3 -m venv --system-site-packages /tmp/npm-packGuKdUa/.env-NmWkkb) failed with status 1:
    #STDERR> 
    #STDOUT> The virtual environment was not created successfully because ensurepip is not
    #STDOUT> available.  On Debian/Ubuntu systems, you need to install the python3-venv
    #STDOUT> package using the following command.
    #STDOUT> 
    #STDOUT>     apt install python3.10-venv
    #STDOUT> 
    #STDOUT> You may need to use sudo with that command.  After installing the python3-venv
    #STDOUT> package, recreate your virtual environment.
    #STDOUT> 
    #STDOUT> Failing command: ['/tmp/npm-packGuKdUa/.env-NmWkkb/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
    #STDOUT> 
    #STDOUT>

      49 |
      50 |   // create the package
    > 51 |   child.execSync('yarn package', { cwd: workdir });
         |         ^
      52 |
      53 |   // this should succeed because the failure script should be ignored
      54 |   const docs = await Documentation.forPackage(path.join(workdir, 'dist', 'js', `${libraryName}@0.0.0.jsii.tgz`), { name: libraryName });

      at ChildProcess.<anonymous> (../../../../tmp/4L5erf/node_modules/jsii-pacmak/lib/util.js:119:27)
error Command failed with exit code 1.
      at Object.<anonymous> (test/docgen/view/documentation.test.ts:51:9)

```

If there is something missing from the bootstrapping process I don't see it in the README and there is no CONTRIBUTING.md

It's not clear on how I can get all tests to pass.

**Comment by mbonig** [comment]
Just took a little `apt install python3.10-venv`  as the error stated and I was rolling again. Hard to believe the solution to my problems was right there in the problem itself =-}
